import { useState } from 'react';
import { BookOpen, Lightbulb, Globe, Factory, RefreshCw, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

const articles = [
  {
    id: 1,
    title: 'What is a Carbon Footprint?',
    icon: Globe,
    content: `A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It's typically measured in tonnes of CO₂ equivalent per year.

Your carbon footprint includes emissions from:
• Direct emissions from burning fossil fuels (driving, heating)
• Indirect emissions from the electricity you use
• Emissions from goods and services you consume
• Transportation of products you buy

The average person's carbon footprint is around 4 tonnes per year globally, but this varies significantly by country and lifestyle.`,
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    id: 2,
    title: 'Why Does It Matter?',
    icon: Lightbulb,
    content: `Climate change is one of the most pressing challenges facing humanity. The greenhouse gases we emit trap heat in our atmosphere, leading to:

• Rising global temperatures
• More frequent extreme weather events
• Rising sea levels
• Loss of biodiversity
• Threats to food and water security

By understanding and reducing our carbon footprint, we can collectively make a significant impact on slowing climate change and protecting our planet for future generations.`,
    color: 'text-warning',
    bgColor: 'bg-warning/10',
  },
  {
    id: 3,
    title: 'Where Do Emissions Come From?',
    icon: Factory,
    content: `Global CO₂ emissions come from various sources:

**Energy & Electricity (25%)**
Power plants burning fossil fuels to generate electricity

**Transportation (16%)**
Cars, trucks, planes, and ships burning petroleum-based fuels

**Industry (21%)**
Manufacturing processes and industrial activities

**Buildings (6%)**
Heating, cooling, and energy use in residential and commercial buildings

**Agriculture (10%)**
Livestock, rice cultivation, and fertilizer use

**Deforestation (11%)**
Clearing forests releases stored carbon

Understanding these sources helps us target the most impactful changes in our daily lives.`,
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
  },
];

const ecoTips = [
  "💡 Switching off lights when leaving a room can save up to 75 kg CO₂ per year",
  "🚿 A 5-minute shower instead of a bath saves around 20 kg CO₂ per month",
  "🥗 One meatless day per week can save 170 kg CO₂ per year",
  "🚲 Cycling instead of driving 10 km saves about 2.5 kg CO₂",
  "🌡️ Lowering your thermostat by 1°C reduces heating emissions by 8%",
  "📦 Buying local products reduces transport emissions by up to 25%",
  "🔌 Unplugging devices when not in use can save 10% on your electricity bill",
  "🌳 Planting one tree absorbs about 22 kg CO₂ per year",
];

const resources = [
  { title: 'IPCC Climate Reports', url: 'https://www.ipcc.ch' },
  { title: 'NASA Climate Change', url: 'https://climate.nasa.gov' },
  { title: 'Carbon Footprint Calculator', url: 'https://www.carbonfootprint.com' },
  { title: 'EPA Climate Resources', url: 'https://www.epa.gov/climate-change' },
];

export default function Learn() {
  const [expandedArticle, setExpandedArticle] = useState<number | null>(1);
  const [currentTip, setCurrentTip] = useState(0);

  const refreshTip = () => {
    setCurrentTip((prev) => (prev + 1) % ecoTips.length);
  };

  return (
    <div className="page-container">
      {/* Header */}
      <div>
        <h1 className="page-title">Learn</h1>
        <p className="page-subtitle">Understanding your environmental impact</p>
      </div>

      {/* Eco Tip of the Day */}
      <div className="dashboard-card gradient-emerald text-primary-foreground">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 bg-primary-foreground/20 rounded-xl flex items-center justify-center">
              <Lightbulb className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-lg font-bold">Eco Tip of the Day</h2>
              <p className="text-primary-foreground/80 text-sm">Small changes, big impact</p>
            </div>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={refreshTip}
            className="text-primary-foreground hover:bg-primary-foreground/20"
          >
            <RefreshCw className="w-5 h-5" />
          </Button>
        </div>
        <p className="text-xl font-medium animate-fade-in">{ecoTips[currentTip]}</p>
      </div>

      {/* Educational Articles */}
      <div>
        <h2 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
          <BookOpen className="w-5 h-5 text-primary" />
          Learn the Basics
        </h2>
        <div className="space-y-4">
          {articles.map((article) => {
            const Icon = article.icon;
            const isExpanded = expandedArticle === article.id;

            return (
              <div key={article.id} className="dashboard-card">
                <button
                  onClick={() => setExpandedArticle(isExpanded ? null : article.id)}
                  className="w-full text-left"
                >
                  <div className="flex items-center gap-4">
                    <div className={cn('w-12 h-12 rounded-xl flex items-center justify-center', article.bgColor)}>
                      <Icon className={cn('w-6 h-6', article.color)} />
                    </div>
                    <div className="flex-1">
                      <h3 className="font-semibold text-foreground">{article.title}</h3>
                      <p className="text-sm text-muted-foreground">
                        {isExpanded ? 'Click to collapse' : 'Click to expand'}
                      </p>
                    </div>
                    <span className={cn(
                      'text-2xl transition-transform duration-200',
                      isExpanded && 'rotate-180'
                    )}>
                      ↓
                    </span>
                  </div>
                </button>

                {isExpanded && (
                  <div className="mt-4 pt-4 border-t border-border animate-fade-in">
                    <div className="prose prose-sm max-w-none">
                      {article.content.split('\n\n').map((paragraph, idx) => (
                        <p key={idx} className="text-muted-foreground mb-3 whitespace-pre-line">
                          {paragraph}
                        </p>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Quick Facts */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { value: '4 tonnes', label: 'Average global footprint/person/year' },
          { value: '2050', label: 'Net zero target for many countries' },
          { value: '1.5°C', label: 'Paris Agreement temperature limit' },
          { value: '50%', label: 'Emissions cut needed by 2030' },
        ].map((fact) => (
          <div key={fact.label} className="dashboard-card text-center">
            <p className="text-2xl font-bold text-primary mb-1">{fact.value}</p>
            <p className="text-xs text-muted-foreground">{fact.label}</p>
          </div>
        ))}
      </div>

      {/* External Resources */}
      <div className="dashboard-card">
        <h3 className="font-semibold text-foreground mb-4">Additional Resources</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {resources.map((resource) => (
            <a
              key={resource.title}
              href={resource.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-between p-3 rounded-lg bg-muted/50 hover:bg-muted transition-colors group"
            >
              <span className="font-medium text-foreground">{resource.title}</span>
              <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors" />
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
